### ISSUE TITLE
Issue Fetching Block Info

### ISSUE THREAD

**Issue by Alexhuszagh** [nemfoundation/nem2-explorer#279] opened 2019-12-19 17:59 UTC
I've queries to ensure all the parameters seem valid, however, under certain cases, the API fails to fetch block info just by querying the block list. @AnthonyLaw, got any information on this?

![Screenshot_20191219_115841](https://user-images.githubusercontent.com/9440903/71197339-ffa8b600-2256-11ea-98d8-31d70629c191.png)

**Comment by AnthonyLaw** [comment] 2019-12-20 03:33
How you reproduce this error?
it seem working fine in my end.

**Comment by AnthonyLaw** [comment] 2020-01-24 11:24
i can't reproduce this error.
assume fixed in master branch.

**Closed by AnthonyLaw** 2020-01-24 11:24 UTC
Labels: story-1
