### ISSUE TITLE
Need Upstream Methods Added to Typescript SDK and Catapult Rest

### ISSUE THREAD

**Issue by Alexhuszagh** [nemfoundation/nem2-explorer#67] opened 2019-09-16 17:13 UTC
In order to simplify our lives, and to get feature parity with the NEM1 block explorer, we would like upstream methods that allow us to. This will be a tracking issue until this functionality is implemented:

1. Get the most recent transactions with limit (unconfirmed and confirmed, as long as filtered by transaction type)
2. Get the most recently defined mosaics with limit.
3. Get the most recently defined namespaces with limit.
4. Get list of accounts sorted by importance with limit.
5. Get list of accounts sorted by number of harvest blocks with limit.

Methods 1-3 allows us to avoid traversing blocks to find corresponding transactions (and in the case of mosaics and namespaces, finding a subset of transactions that match `MosaicDefinitionTransaction` and `RegisterNamespaceTransaction`, respectively). Methods 4 and 5 avoid having to enumerate through all accounts to list significant accounts and harvesters.

# Method Specifics

**General**

Shared limit enumeration for all transactions with a limit. If the limit is not provided, default to `N_25`.

```js
/**
 * Number of returned limits:
 * N_25: 25 results.
 * N_50: 50 results.
 * N_75: 75 results.
 * N_100: 100 results.
 */
export declare enum LimitType {
    N_25 = 25,
    N_50 = 50,
    N_75 = 75,
    N_100 = 100,
}
```

**Confirmed Transactions**

Get N confirmed transactions from the transaction hash, up to (non-inclusive) the provided hash. If the hash is not provided, default to `max` and return the N latest confirmed transactions.

```js
getConfirmedTransactionsFromHashWithLimit(hash?: string, limit?: LimitType): Observable<Transaction[]>;
```

This should match the rest endpoint:

```
/transactions/confirmed/{hash}/limit/{limit}
```

**Confirmed Transactions By Type**

Get N confirmed transactions by type from the transaction hash, up to (non-inclusive) the provided hash. If the hash is not provided, default to `max` and return the N latest confirmed transactions that match the transaction type.

```js
getConfirmedTransactionsFromHashWithLimitByType(type: TransactionType, hash?: string, limit?: LimitType): Observable<Transaction[]>;
```

This should match the rest endpoint (where type is a string like `"transfer"` describing the transaction type):

```
/transactions/confirmed/{hash}/limit/{limit}/type/{type}
```

**Unconfirmed Transactions**

Get N unconfirmed transactions from the transaction hash, up to (non-inclusive) the provided hash. If the hash is not provided, default to `max` and return the N latest unconfirmed transactions.

```js
getUnconfirmedTransactionsFromHashWithLimit(hash?: string, limit?: LimitType): Observable<Transaction[]>;
```

This should match the rest endpoint:

```
/transactions/unconfirmed/{hash}/limit/{limit}
```

**Mosaics**

Get N defined mosaics from the mosaic ID, up to (non-inclusive) the provided ID. If the ID is not provided,  default to `max` and return the N latest defined mosaics. The ID should be provided as a hex string.

```js
getMosaicsFromIdWithLimit(id?: string, limit?: LimitType): Observable<MosaicInfo[]>;
```

This should match the rest endpoint:

```
/mosaics/{id}/limit/{limit}
```

**Namespaces**

Get N registered namespaces from the namespace ID, up to (non-inclusive) the provided ID. If the ID is not provided, default to `max` and return the N latest defined namespaces. The ID should be provided as a hex string.

```js
getNamespacesFromIdWithLimit(id?: string, limit?: LimitType): Observable<NamespaceInfo[]>;
```

This should match the rest endpoint:

```
/namespaces/{id}/limit/{limit}
```

**Richest Accounts**

Get the N richest accounts by importance, up to (non-inclusive) the provided address or public key. If the address/public-key is not provided, default to `max` and return the N richest accounts. The address should be provided as a base32-encoded string. The public-key should be provided as a hex-encoded public key.

```js
getAccountsByImportanceFromAddressWithLimit(address?: string, limit?: LimitType): Observable<AccountInfo[]>;
getAccountsByImportanceFromPublicKeyWithLimit(publicKey?: string, limit?: LimitType): Observable<AccountInfo[]>;
```

This should match the rest endpoint:

```
/accounts/importance/{address}/limit/{limit}
/accounts/importance/{publicKey}/limit/{limit}
```

**Most Harvested Accounts**

Get the N richest accounts by number of harvested blocks, up to (non-inclusive) the provided address or public key. If the address/public-key is not provided, default to `max` and return N accounts with the most harvested blocks. The address should be provided as a base32-encoded string. The public-key should be provided as a hex-encoded public key.

```js
getAccountsByHarvestedBlocksFromAddressWithLimit(address?: string, limit?: LimitType): Observable<AccountInfo[]>;
getAccountsByHarvestedBlocksFromPublicKeyWithLimit(publicKey?: string, limit?: LimitType): Observable<AccountInfo[]>;
```

This should match the rest endpoint:

```
/accounts/harvested/{address}/limit/{limit}
/accounts/harvested/{publicKey}/limit/{limit}
```

**Comment by Alexhuszagh** [comment] 2019-09-16 17:18
We also need to think about new routes for catapult-rest and then integrating these methods into the typescript SDK. I believe suitable endpoints would be:

1. getTransactionsFromHashWithLimit
  - `'/transactions/latest/limit/{limit}'`
  - `'/transactions/{hash}/limit/{limit}'`
2. getMosaicsFromIdWithLimit
  - `'/mosaics/latest/limit/{limit}'`
  - `'/mosaics/{hash}/limit/{limit}'`
3. getNamespacesFromIdWithLimit
  - `'/namespaces/latest/limit/{limit}'`
  - `'/namespaces/{hash}/limit/{limit}'`

**Comment by Alexhuszagh** [comment] 2019-09-16 17:25
We also need a list of known peers (preferably, any supernodes), potentially a list of accounts sorted by importance (with limit, analogous to [rich list](http://explorer.nemtool.com/#/accountlist)), and a list of accounts sorted by the number of harvest blocks (with limit, analogous to [harvester list](http://explorer.nemtool.com/#/harvesterlist)).

We also need to filter transactions to allow for:
1. Unconfirmed transactions
2. By transaction type (this should be handled at the REST level ideally).

**Comment by Alexhuszagh** [comment] 2019-09-16 18:00
Please leave any suggestions on what may be improved. Some notable things that might be changed:

1. Is the naming scheme correct? Do we want to change the names of individual methods, or change the order of limit/type, etc?
2. Do we need the account rich/harvester list?

**Comment by AnthonyLaw** [comment] 2019-09-17 09:01
Hi there, thanks for adding it.
Here is my opinion.

1. Follow current [rest endpoint](https://nemtech.github.io/endpoints.html) pattern should be

**Confirmed Transactions**
>/transactions/confirmed/{hash}/limit/{limit}
>/transactions/confirmed/{hash}/limit/{limit}/type/{type}

```
/transactions/{hash}/confirmed/limit/{limit}
/transactions/{hash}/confirmed/limit/{limit}/type/{type}
```

**Unconfirmed Transactions**
>/transactions/unconfirmed/{hash}/limit/{limit}
```/transactions/{hash}/unconfirmed/limit/{limit}```

**Richest Accounts**
>/accounts/importance/{address}/limit/{limit}
>/accounts/importance/{publicKey}/limit/{limit}
```
/accounts/{address}/importance/limit/{limit}
/accounts/{publicKey}/importance/limit/{limit}
```

**Most Harvested Accounts**

>/accounts/harvested/{address}/limit/{limit}
>/accounts/harvested/{publicKey}/limit/{limit}
```
/accounts/{address}/harvested/limit/{limit}
/accounts/{publicKey}/harvested/limit/{limit}
```

2. **Change** `limit?: LimitType` to [queryParams?: QueryParams](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/QueryParams.ts).
```
getConfirmedTransactionsFromHashWithLimit(hash?: string, queryParams?: QueryParams): Observable<Transaction[]>;
getConfirmedTransactionsFromHashWithLimitByType(type: TransactionType, hash?: string, queryParams?: QueryParams): Observable<Transaction[]>;
```

**Reason** 
`LimitType` can replace by `queryParams.pageSize`, and retrive transactions/namespaces/mosaics list as pagination by  `queryParams.id`

**Remark**
Check with this [Transaction](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/2601e1982ceec47ff1cf58d0d8776ddd2dac5a60/src/infrastructure/AccountRepository.ts#L92)  and [Namespace](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/dd45ca1864cedc8a26893343ebaeb4dee6459081/src/infrastructure/NamespaceRepository.ts#L46) but `Mosaics` i'm not sure.


3. Richest accounts should get `Higher Balance` from the account, rather than by `importance`,
we may add another `ImportanceList`
>```
>getAccountsByImportanceFromAddressWithLimit(address?: string, limit?: LimitType): Observable<AccountInfo[]>;
>getAccountsByImportanceFromPublicKeyWithLimit(publicKey?: string, limit?: LimitType): Observable<AccountInfo[]>;
>```
I dont think it need `address?: string` and `publicKey?: string` because, it should search from account table, and order by balance, return as a list.

**Suggest**
```
getRichList(mosaicId: MosaicId || namespaceId: NamespaceId,  queryParams?: QueryParams): Observable<AccountInfo[]>;
```
rest endpoint
```
/accounts/{mosaicId}/richlist
```

**Reason**
We can alway request richList from different mosaicId / LinkedMosaicId, it's helpful for project who build on chain.

4. **Most Harvested Accounts**

for harvesterList should have use same concept with rich list.

```
getHarvesterList(queryParams?: QueryParams): Observable<AccountInfo[]>;
```
rest endpoint
```
/harvester/
```

5. ** getHarvestedBlocksInfoFromAccount**

>```
>getAccountsByHarvestedBlocksFromAddressWithLimit(address?: string, limit?: LimitType): Observable<AccountInfo[]>;
>getAccountsByHarvestedBlocksFromPublicKeyWithLimit(publicKey?: string, limit?: LimitType): Observable<AccountInfo[]>;
>```

**Suggest**
```
getHarvestedBlocksInfoFromAccount(accountIds: Address[],  queryParams?: QueryParams): Observable<AccountInfo[]>;
```
- Return harvested blocks list
- [accountIds](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/2601e1982ceec47ff1cf58d0d8776ddd2dac5a60/src/infrastructure/model/accountIds.ts) params should accept Address | publicKey

**Comment by Alexhuszagh** [comment] 2019-09-18 17:45
@AnthonyLaw Great suggestions, I like the idea. If there are no other comments, I'll adopt those changes.

**Comment by Alexhuszagh** [comment] 2019-09-19 23:53
The more I've thought about it, the more I think we need a slightly better API for this.
@dgarcia360, @evias, would there be any way to implement a cursor or page-like API request in catapult-rest? A pretty good crash course for this is the [Twitter API](https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines), which we have a slightly different take on.

The general idea (for a cursor) is as follows: say I want to get all transactions that occurred **after** block height `15`, and want to get only `25` values. Ideally, in a perfect world, I would make a request like follows:

```
GET /blocks/since/{height=15}/limit/{limit=25}
``` 

Which should get me blocks 16-40.

Now, say I want every block **before** block height `41`, and only want to get `25` values.  Likewise, I'd make a request like this:

```
GET /blocks/max/{height=41}/limit/{limit=25}
```

Which should get me blocks 16-40.

# Why not Just Calculate the Block Height?

Sure, this works, for the block height. It doesn't work for transaction hashes, mosaic IDs, namespace IDs, etc.

# Non-Inclusive or Inclusive

I believe these requests should be non-inclusive, with an optional default keyword to specify the latest values. This way, initial requests can be made without a separate request to get the chain height, or the latest transaction hash, and from the last known valid value in the client, we can make a request to get unique data before or after the currently held data. This keyword would likely be `max` or `latest`, as discussed previously.

**Comment by evias** [comment] 2019-09-20 08:29
I am thinking about this and trying to determine what part could be taken up by SDK.

For instance, anything that is paginating, is already supported in REST so wrapping filters around `max`, `since`, `latest`, `oldest`, etc. seems feasible in SDK.

What do you think? 

Seems like its not a blocker issue (at least the pagination things) - anything that is missing in REST obviously needs addressing asap though :+1:

**Comment by evias** [comment] 2019-11-04 09:09
merged in master

**Closed by evias** 2019-11-04 09:09 UTC
